/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kkishore' at '7/18/16 3:32 PM' with Gradle 2.14
 *
 * @author kkishore, @date 7/18/16 3:32 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
